### ISSUE TITLE
Unable to start minecraft.

### ISSUE THREAD

**Issue by fenrave** [Admicos/minecraft-wayland#10]
```[11:46:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:46:23] [Render thread/INFO]: Setting user: FenRave
[11:46:23] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[11:46:23] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[11:46:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:46:23] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
[11:46:23] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GLX.getOpenGLVersionString(SourceFile:35)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.getApiDescription(SourceFile:770)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at dvp.a(SourceFile:2418)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at dvp.a(SourceFile:2412)
[11:46:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:187)
[11:46:23] [Render thread/INFO]: [STDERR]: 	... 8 more
[11:46:23] [Render thread/INFO]: [STDOUT]: Exiting with -1
```
I'm clueless on how to get past this issue. Seems like the patched GLFW version doesn't initialize. Might try building it myself to see if its an issue with the rpm package.

**Comment by fenrave** [comment]
ayo scratch all of that, the library was put in lib64, but dear god 
![image](https://user-images.githubusercontent.com/40793346/141692528-b73d8aee-28c1-496e-820e-8446b5a89842.png)
