### ISSUE TITLE
Issue with Nvidia on Wayland on Gnome

### ISSUE THREAD

**Issue by nonetrix** [Admicos/minecraft-wayland#15]
I followed the steps it was able to spawn a black window but instantly crashes with this
```
MultiMC version: 0.6.14-2998


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.226.92.72]

session.minecraft.net resolves to:
    [34.205.58.168, 52.21.65.46, 3.213.200.53]

textures.minecraft.net resolves to:
    [13.32.151.56, 13.32.151.11, 13.32.151.2, 13.32.151.80]

api.mojang.com resolves to:
    [13.249.107.137]


Minecraft folder is:
/home/nonetrix/.local/share/multimc/instances/1.18.1/.minecraft


Java path is:
/usr/lib64/jvm/java-17-openjdk/bin/java


Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from N/A.


AMD Ryzen 7 3700X 8-Core Processor
NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)

Subsystem: Micro-Star International Co., Ltd. [MSI] Device 3362

Kernel driver in use: nvidia

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/nonetrix/.local/share/multimc/instances/1.18.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Using system GLFW.

Libraries:
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home/nonetrix/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  /home/nonetrix/.local/share/multimc/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  /home/nonetrix/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  /home/nonetrix/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /home/nonetrix/.local/share/multimc/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/nonetrix/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/nonetrix/.local/share/multimc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/nonetrix/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/nonetrix/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/nonetrix/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/nonetrix/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/nonetrix/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/nonetrix/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/nonetrix/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/nonetrix/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  /home/nonetrix/.local/share/multimc/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  /home/nonetrix/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  /home/nonetrix/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/nonetrix/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/nonetrix/.local/share/multimc/instances/1.18.1/.minecraft --assetsDir /home/nonetrix/.local/share/multimc/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 27189


Using onesix launcher.

[20:45:53] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[20:45:53] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[20:45:57] [main/INFO]: Loading 3 mods:
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
[20:45:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/nonetrix/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[20:45:59] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:46:00] [Render thread/INFO]: Setting user: NonetrixWasTaken
[20:46:00] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/28/21, 8:46 PM
Description: Initializing game

java.lang.RuntimeException: GL_FRAMEBUFFER_UNSUPPORTED
	at net.minecraft.class_276.method_1239(class_276.java:175)
	at net.minecraft.class_6364.method_36802(class_6364.java:60)
	at net.minecraft.class_6364.<init>(class_6364.java:25)
	at net.minecraft.class_310.<init>(class_310.java:500)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_276.method_1239(class_276.java:175)
	at net.minecraft.class_6364.method_36802(class_6364.java:60)
	at net.minecraft.class_6364.<init>(class_6364.java:25)
	at net.minecraft.class_310.<init>(class_310.java:500)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.15.11-arch2-1
	Java Version: 17.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 601612536 bytes (573 MiB) / 1049624576 bytes (1001 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GP104 [GeForce GTX 1080]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16053.83
	Virtual memory used (MB): 4717.88
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 495.46, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
#@!@# Game crashed! Crash report saved to: #@!@# /home/nonetrix/.local/share/multimc/instances/1.18.1/.minecraft/crash-reports/crash-2021-12-28_20.46.01-client.txt
Process exited with code 255.
Clipboard copy at: 28 Dec 2021 20:47:53 -0600

```

**Comment by nonetrix** [comment]
This issue happens with xwayland it seems my system might be misconfigured somehow sorry
