### ISSUE TITLE
Crash on startup with 1.19 only

### ISSUE THREAD

**Issue by CozzyBro2** [Admicos/minecraft-wayland#25]
Minecraft crashes on 1.19 when attempting to launch from multimc using native glfw libraries, an identical 1.18.2 instance (aside from game version) works normally.

Full crash log:
```
MultiMC version: 0.6.15-3244


Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.46.48, 65.8.46.62, 65.8.46.49, 65.8.46.45]

session.minecraft.net resolves to:
    [54.173.66.187, 52.7.153.255, 54.164.34.185]

textures.minecraft.net resolves to:
    [18.160.200.72, 18.160.200.51, 18.160.200.11, 18.160.200.107]

api.mojang.com resolves to:
    [13.226.22.116, 13.226.22.16, 13.226.22.37, 13.226.22.46]


Minecraft folder is:
/home/archy/.local/share/multimc/instances/1.19/.minecraft


Java path is:
/usr/lib64/jvm/java-18-openjdk/bin/java


Checking Java version...
Java is version 18.0.1.1, using 64-bit architecture, from N/A.


AMD FX(tm)-6300 Six-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] (rev e5)

Subsystem: Tul Corporation / PowerColor Device 2385

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.1

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/archy/.local/share/multimc/instances/1.19/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Using system GLFW.

Libraries:
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/archy/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/archy/.local/share/multimc/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/archy/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/archy/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/archy/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /home/archy/.local/share/multimc/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/archy/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /home/archy/.local/share/multimc/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-x86_64.jar
  /home/archy/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/archy/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/archy/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/archy/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/archy/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /home/archy/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/authlib/3.5.41/authlib-3.5.41.jar
  /home/archy/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/archy/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/archy/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/archy/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/archy/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/archy/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/archy/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/intermediary/1.19/intermediary-1.19.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/archy/.local/share/multimc/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /home/archy/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /home/archy/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /home/archy/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /home/archy/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /home/archy/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.14.6/fabric-loader-0.14.6.jar
  /home/archy/.local/share/multimc/libraries/com/mojang/minecraft/1.19/minecraft-1.19-client.jar

Native libraries:
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-linux.jar
  /home/archy/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-linux.jar

Mods:
  [❌] c2me-fabric-mc1.19-0.2.0+alpha.7.56.jar (disabled)
  [✔️] iris-mc1.19-1.2.5
  [✔️] krypton-0.2.0
  [✔️] lithium-fabric-mc1.19-0.8.0-SNAPSHOT
  [✔️] sodium-fabric-mc1.19-0.4.2+build.16
  [✔️] starlight-1.1.0+fabric.eb9df34
  [❌] vmp-fabric-mc1.19-0.2.0+beta.3.25-all.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir /home/archy/.local/share/multimc/instances/1.19/.minecraft --assetsDir /home/archy/.local/share/multimc/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms1512m, -Xmx4096m, -Duser.language=en]


Wrapper command is:
gamemoderun


Minecraft process ID: 3065


Using onesix launcher.

[20:14:32] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.6
[20:14:33] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 3.0.4+9ff28f4057 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[20:14:33] [main/INFO]: Loading 16 mods:
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- fabric-api-base 0.4.8+e62f51a357 via sodium
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2 via iris
	- fabric-rendering-data-attachment-v1 0.3.11+9ff28f4057 via sodium
	- fabric-rendering-fluids-v1 3.0.4+9ff28f4057 via sodium
	- fabric-resource-loader-v0 0.5.2+9e7660c657 via sodium
	- fabricloader 0.14.6
	- iris 1.2.5
	- java 18
	- krypton 0.2.0
	- lithium 0.8.0-SNAPSHOT
	- minecraft 1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.2+build.16
	- starlight 1.1.0+fabric.eb9df34
[20:14:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/archy/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:14:33] [main/INFO]: Compatibility level set to JAVA_16
[20:14:33] [main/INFO]: Compatibility level set to JAVA_17
[20:14:33] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 1 override(s) found
[20:14:33] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[20:14:34] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[20:14:34] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[20:14:35] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[20:14:35] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:14:39] [main/INFO]: Building optimized datafixer
[20:14:43] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[20:14:43] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:14:45] [Render thread/INFO]: Setting user: HashCollision
[20:14:45] [Render thread/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[20:14:45] [Render thread/INFO]: Krypton is now accelerating your Minecraft client's networking stack 🚀
[20:14:45] [Render thread/INFO]: Note that Krypton is most effective on servers, not the client.
[20:14:45] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[20:14:46] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/8/22, 8:14 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at net.minecraft.class_1041.method_4492(class_1041.java:135)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:826)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:129)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:122)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at net.minecraft.class_1041.method_4492(class_1041.java:135)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:826)
	at net.minecraft.class_310.<init>(class_310.java:465)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.18.2-zen1-1-zen
	Java Version: 18.0.1.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1870659584 bytes (1784 MiB) / 2325741568 bytes (2218 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-6300 Six-Core Processor
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x67ef
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8046.76
	Virtual memory used (MB): 2666.73
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms1512m -Xmx4096m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/archy/.local/share/multimc/instances/1.19/.minecraft/crash-reports/crash-2022-06-08_20.14.46-client.txt
Process exited with code 255.
Clipboard copy at: 08 Jun 2022 20:16:43 -0400
```

**Comment by Admicos** [comment]
1.18.2 uses LWJGL 3.2.2, 1.19 uses 3.3.1 (according to PolyMC), and the change seems to have happened at 3.3.0 (https://github.com/LWJGL/lwjgl3/blob/6540c966fdd9ad3b108f351deb41d3b5fe99e9ab/doc/notes/3.3.0.md)

**Comment by Admicos** [comment]
LWJGL claims they updated to 3.3.5, while this package is at 3.3.7, so it should've worked

**Comment by Admicos** [comment]
Can you try the `one-nineteen` branch? It's incompatible with libdecor (because the decor patches are not up to date), but it should fix 1.19.

**Comment by lilithium-hydride** [comment]
I tried the branch and it appears to work perfectly. Artix Linux, Sway, NVIDIA proprietary (`515.43.04-1`).

**Comment by lilithium-hydride** [comment]
That's interesting, mine is the same way. I didn't bother to check earlier, assuming that stable gameplay would indicate it was working. Unmodified GLFW was giving me a lot of graphical issues (and some sound issues, oddly enough), but it's mostly down to 1.18+`glfw-wayland-minecraft` levels of glitchiness for me now.

**Comment by Admicos** [comment]
As a quick workaround, put `env -u DISPLAY` in your wrapper command field. I forgot the latest versions of GLFW can choose Wayland on runtime. I'll probably patch it to force wayland

**Comment by lilithium-hydride** [comment]
Ah, that explains it! Everything seems to be working again (for real this time).

**Comment by Admicos** [comment]
https://github.com/Admicos/minecraft-wayland/issues/31

**Comment by Lassebq** [comment]
Same crash in 1.19 and 1.20, using main branch
