### ISSUE TITLE
PLEASE TEST: one-nineteen branch with 1.18 and older

### ISSUE THREAD

**Issue by Admicos** [Admicos/minecraft-wayland#31]
If you need libdecor, pull in #29 

I've just realized this should work. `libdecoration` branch is an unstable git snapshot of GLFW, and that seems to work reasonably well with <1.18.

If this works, `one-nineteen` (which is also an unstable git snapshot) and `main` (1.18.x & older) could be merged into one version.

Using an unstable git snapshot was also the reason on separating libdecor support on it's own branch, which may be merged to the `main` branch if nothing goes wrong.

**Comment by tauin** [comment]
it seems to be working (with the libdecor patches from #29 which where frankly just annoying to set up)
![Screenshot from 2022-12-11 05-36-11](https://user-images.githubusercontent.com/71744831/206876562-9ae224fc-9500-4f81-94bf-fc9ec68b7516.png)

**Comment by Lassebq** [comment]
Nothing seems to work for me. I tried both main and one-nineteen, with 1.20 and 1.19
one-nineteen gives this error in both versions
```
edh$a: GLFW error 65544: EGL: Failed to clear current context: An EGLDisplay argument does not name a valid EGL display connection
	at edh.b(SourceFile:218) ~[1.19.3.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at edh.<init>(SourceFile:93) ~[1.19.3.jar:?]
	at fek.a(SourceFile:21) ~[1.19.3.jar:?]
	at ejf.<init>(SourceFile:490) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
```
And main one crashes with the same crash as in #25 (both versions too)

I'm using arch linux with nvidia graphics card

**Comment by Lassebq** [comment]
1.13 just gives a crash dump, nothing useful other than
```
# Problematic frame:
# C  [liblwjgl_opengl.so+0x48979]  Java_org_lwjgl_opengl_GL11_nglGetString+0x9
```

**Comment by ExistingProgrammer** [comment]
> Nothing seems to work for me. I tried both main and one-nineteen, with 1.20 and 1.19 one-nineteen gives this error in both versions
> 
> ```
> edh$a: GLFW error 65544: EGL: Failed to clear current context: An EGLDisplay argument does not name a valid EGL display connection
> 	at edh.b(SourceFile:218) ~[1.19.3.jar:?]
> 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
> 	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar:build 7]
> 	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar:build 7]
> 	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar:build 7]
> 	at edh.<init>(SourceFile:93) ~[1.19.3.jar:?]
> 	at fek.a(SourceFile:21) ~[1.19.3.jar:?]
> 	at ejf.<init>(SourceFile:490) ~[1.19.3.jar:?]
> 	at net.minecraft.client.main.Main.a(SourceFile:205) ~[1.19.3.jar:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
> ```
> 
> And main one crashes with the same crash as in #25 (both versions too) 1.18 is affected too.
> 
> I'm using arch linux with nvidia graphics card

Am also getting this error with wayland on nvidia card on 1.18 forge modpack. Is there any solution?
