### ISSUE TITLE
crash on startup 1.19.4

### ISSUE THREAD

**Issue by Dialgatrainer02** [Admicos/minecraft-wayland#50]
minecraft ver:1.19.4
glfw : aur patched 
error: 
Description: Initializing game
java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at net.minecraft.class_1041.method_4492(class_1041.java:140)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:844)
	at net.minecraft.class_310.<init>(class_310.java:493)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:129)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:122)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 13 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at net.minecraft.class_1041.method_4492(class_1041.java:140)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:844)
	at net.minecraft.class_310.<init>(class_310.java:493)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)``

**Comment by Lassebq** [comment]
Same here.

**Comment by ZerdoX-x** [comment]
@Dialgatrainer02 @Lassebq see https://github.com/Admicos/minecraft-wayland/issues/54#issuecomment-1722715553

Also duplicate of https://github.com/Admicos/minecraft-wayland/issues/37 #36 #25
