### ISSUE TITLE
Crash on Prism Launcher Flatpak in 1.20.6 

### ISSUE THREAD

**Issue by SusStew** [Admicos/minecraft-wayland#64]
I am using the Flatpak of Prism Launcher on Nobara Linux, with KDE Plasma on Wayland.
When running the game, I get the following crash report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-06-06 02:40:32
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]Wayland: Failed to connect to display
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:78)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:846)
	at ffh.<init>(SourceFile:509)
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:78)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:846)
	at ffh.<init>(SourceFile:509)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Linux (amd64) version 6.8.12-200.fsync.fc39.x86_64
	Java Version: 21.0.3, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 346993568 bytes (330 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 8448.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 28430.68
	Virtual memory used (MB): 7383.18
	Swap memory total (MB): 20479.99
	Swap memory used (MB): 1214.25
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.20.6
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3+5
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>
```
This is in vanilla, but the same thing happens with mods. Interestingly, on 1.20.1, I get a similar error, but the first line is different: 
```
java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140422951197856
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:75)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:844)
	at emh.<init>(SourceFile:493)
	at net.minecraft.client.main.Main.main(SourceFile:198)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**The appimage version of Prism Launcher does work and launches the game as native Wayland.**

**Comment by ByPaco10** [comment]
Can confirm on arch linux and 1.16.5

**Comment by LemonHeadOnGit** [comment]
Having the same issue, but would this not be better suited to the [PrismLauncher flatpak repository](https://github.com/flathub/org.prismlauncher.PrismLauncher), considering its a flatpak-specific issue?

I did make an issue regarding this in the repo: https://github.com/flathub/org.prismlauncher.PrismLauncher/issues/67
