### ISSUE TITLE
java.lang.IllegalStateException: GLFW error before init: [0x1000C]Wayland: The platform does not provide the window position

### ISSUE THREAD

**Issue by lwb-2021** [Admicos/minecraft-wayland#65]
```
Description: Initializing game

java.lang.IllegalStateException: GLFW error before init: [0x1000C]Wayland: The platform does not provide the window position
	at com.mojang.blaze3d.platform.GLX.lambda$_initGlfw$0(GLX.java:60) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85407_(Window.java:133) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-
...
A detailed walkthrough of the error, its code path and all known details is as follows:
-------------------------------------------------------------------------
-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at com.mojang.blaze3d.platform.GLX.lambda$_initGlfw$0(GLX.java:60) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85407_(Window.java:133) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WindowMixin,pl:mixin:APP:embeddiumextras.mixin.json:borderless.BorderlessWindowMixin,pl:mixin:APP:embeddiumextras.mixin.json:borderless.accessors.MainWindowAccessor,pl:mixin:APP:embeddium.mixins.json:workarounds.context_creation.WindowMixin,pl:mixin:APP:mixins.oculus.json:MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?] {re:classloading}
...
-- Initialization --
Details:
	Modules: 
Stacktrace:...
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.9.6-zen1-1-zen
	Java Version: 17.0.11, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 9592770880 bytes (9148 MiB) / 10737418240 bytes (10240 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x191b
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GM107M [GeForce GTX 960M]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x139b
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 24337.50
	Virtual memory used (MB): 14283.26
	Swap memory total (MB): 16383.00
	Swap memory used (MB): 4365.25
	JVM Flags: 2 total; -Xms10240M -Xmx10240M
	Launched Version: 1.20.1-forge-47.2.20
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
```
This error occurpted when I tried to play ATM9 on wayland, I do all things the README.MD described, but they did not work

**Comment by lwb-2021** [comment]
I've searching for some solutions on the Internet. 
I think patching this function may be helpful
```c
void _glfwGetWindowPosWayland(_GLFWwindow* window, int* xpos, int* ypos);
```

**Comment by masDO1337** [comment]
```java.lang.IllegalStateException: GLFW error before init: [0x1000C]Wayland: The platform does not provide the window position```

i also got the same problem. is there an update?

**Comment by masDO1337** [comment]
I solved the problem, I just had to change the launcher from Multimc to Prism Launcher

**Comment by Shapaper233** [comment]
https://github.com/neoforged/NeoForge/issues/657#issuecomment-2015258601
This can solve the problem.
